### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bluin4308** [OneLiL05/nurekit#1]
Неправильний переклад слова "аудиторія" на англійську.
https://dictionary.cambridge.org/dictionary/english/auditory
Треба використати "auditorium" або синонім
https://dictionary.cambridge.org/dictionary/english/auditorium

**Comment by OneLiL05** [comment]
Привіт, дякую за зворотний зв'язок, обовʼязково виправлю найближчим часом

**Comment by ketronix-dev** [comment]
![2023-09-04_18-01](https://github.com/OneLiL05/nurekit/assets/111521698/04da8042-bcb9-4ed1-9e5c-86014274ed46)
Так також можна писати
