### ISSUE TITLE
feat: Спростити інтерфейс метода findOne

### ISSUE THREAD

**Issue by bluin4308** [OneLiL05/nurekit#5]
Чи справді потрібно передавати `name` в `findOne` як поле об'єкта? Наразі в цьому нема сенсу. Якщо `findOne` не планується розширювати в майбутньому, може варто випилити `interface FindOneParams`?

**Comment by OneLiL05** [comment]
Привіт, можливо ти правий, бо наразі ніякого розширення методу `findOne` не передбачується, а робити цей метод невиправдано складним не має сенсу.
